Prefix: "&8[&bOneBlock&8] "

Database:
  hote: ""
  databaseName: ""
  username: ""
  password: ""
  port: 3306

Island:
  level:
    1:
      size: 100
      blocks:
        - "DIRT"
        - "COAL_ORE"
        - "OAK_WOOD"
        - "STONE"